gz/rust-cpuid

src/lib.rs

The `#![no_std]` attribute now injects extern crate core at the top of
the crate as well as the libcore prelude into all modules.

Fixes errors in latest nightly (1.4.0-nightly (e5d90d984 2015-08-07)).

---

src/lib.rs

Using Slice struct has been deprecated since rust 1.9.
https://doc.rust-lang.org/core/raw/struct.Slice.html
Switch to using core::slice::from_raw_parts

Fix deprecate warnings with the latest nightly

---

src/lib.rs

See Intel Vol. 2A, Table 3.13.
Fixes question mark characters in extended brand string (e.g. when using raw_cpuid under QEMU).

Consider the terminating NULL character of the extended brand string instead of always going for the 48 characters.

---

src/lib.rs

Add an has_rdseed property and deprecate the has_rdseet typo

---

src/lib.rs

Intel ISA reference manual says:
> A processor supports Intel SHA extensions if
> CPUID.(EAX=07H, ECX=0):EBX.SHA [bit 29] = 1. The SHA extensions require only
> XMM state support on operating systems, similar to SSE2 instructions.
See also the Wikipedia summary: https://en.wikipedia.org/wiki/Intel_SHA_extensions

Detect Intel SHA Extensions

---

Cargo.toml
build.rs
src/lib.rs

This pull request implements the suggestions in #19. It replaces the ASM-based implementation of `cpuid` on nightly with one which calls the Rust `core::arch::{x86, x86_64}::__cpuid_count` function.
Note that since the standard function only allows us to change EAX and ECX, but not EBX or EDX, I've removed the `cpuid1` / `cpuid2` functions.

Migrate to `core::arch` for cpuid on nightly

---

src/bin/cpuid.rs
src/lib.rs

This contains the information from leaf 0x8000001F as defined on page
632 of the AMD64 Architecture Programmer’s Manual Volume 3:
General-Purpose and System Instructions.
https://www.amd.com/system/files/TechDocs/24594.pdf

Add support for AMD Memory Encryption information

---

Cargo.toml
examples/tsc_frequency.rs
src/lib.rs
src/tests.rs

Fixes #31, avoids accidential division by zero for clients.

Return Option<u64> for get_tsc_frequency.

---

src/lib.rs

This bit has been reserved by Intel & AMD for use by hypervisors, and indicates the presence of a hypervisor.

add support of the hypervisor present bit

---

src/lib.rs

When iterating the SGX sub-leafs, make sure ECX starts from 2.
https://github.com/gz/rust-cpuid/blob/6554bb914214934b15cccb9d8be4d0f71ac69232/src/lib.rs#L3557-L3567

ECX starts from 2 when iterating the SGX sub-leafs

---

src/lib.rs

Also adding comments explaining why all safety requirements are now met, and explicitly annotating the types of the byte slices.

Fix unsound transmutes (fixes #40)

---

src/lib.rs

~Is it intentional that the conversion in `as_bytes()` depends on the endianness?~
~If yes, there should maybe be a comment mentioning it.~
~I *think* it is not, so it may be best to replace it with a (not much longer) version without unsafe.~
Nevermind the endianness question. I guess x86 is just always little endian. I believe it's still best to avoid unsafe code, when the safe version is not significantly longer or slower.

Replace as_bytes with safe code

---

src/lib.rs

A possible fix for #41.
Unfortunately this would break compilation for 32-bit targets without SSE, a few of which would support CPUID. Proper runtime detection would look like https://doc.rust-lang.org/stable/src/core/up/up/stdarch/crates/core_arch/src/x86/cpuid.rs.html#110-156, but needs C again, to accomplish it on stable Rust.

Break compilation on SGX and 32-bit x86 without SSE (fixes #41)

---

src/lib.rs

I added a few doc comments how the VendorInfo-String works because I just think this is really interesting. 
What do you think?

added vendor info comments

---

src/lib.rs
src/tests/i5_3337u.rs

Hi! In my opinion this crate missed comprehensive debug impls for all structs. I changed all outputs for eax, ebx etc. to hex-based outputs and invoke all important methods for each struct and would like to propose you this MR.
**ONLY BLOCKER SO FAR**: Similar to the std vector, `vec::iter()` should print all elements of the iterator when debug-formatted. This is currently not possible, because I didn't found a nice way to solve this in code. 
Example debug output of `CpuId::new()` on my system with the new code:
```
CpuId {
vendor: Intel,
supported_leafs: 0x000000000000001b,
vendor_info: Some(
VendorInfo {
ebx: 0x00000000756e6547,
edx: 0x0000000049656e69,
ecx: 0x000000006c65746e,
brand_string: "GenuineIntel",
},
),
feature_info: Some(
FeatureInfo {
eax: 0x00000000000806c1,
ebx: …
```

Comprehensive Debug-impls for all structs

---

src/lib.rs

Sorry, in the last PR I missed to correctly implement debug formatting for SgxSectionIter. Now all iterators should get debug-printed in a pretty way.

fixed debug-fmt for SgxSectionIter

---

src/lib.rs

This PR adds QEMU as hypervisor type. QEMU is the hypervisor type, if QEMU is used without KVM as accelerator.  
PS: Third-party dependents [[0]] of this lib implemented this manually. I think it would be smart to upstream some of this into this crate.
[0]: https://github.com/heim-rs/heim/blob/master/heim-virt/src/sys/linux/cpuid.rs#L21

add QEMU + other common values as hypervisor type

---

src/lib.rs

PR linked to https://github.com/gz/rust-cpuid/issues/52

get_hypervisor_info: only returns if hypervisor-flag is set

---

CHANGELOG.md
README.md
examples/cpu.rs
examples/topology.rs
examples/tsc_frequency.rs
src/bin/cpuid.rs
src/extended.rs
src/lib.rs
src/tests/i5_3337u.rs
src/tests/ryzen_matisse.rs

AMD support

---

CHANGELOG.md
src/bin/cpuid.rs
src/lib.rs
src/tests/ryzen_matisse.rs
src/tests/xeon_gold_6252.rs

I added ExtendedFeatures::has_avx512vnni().
But I have no avx512vnni enabled CPUs.
How do I test this?

Add ExtendedFeatures::has_avx512vnni().

---

Cargo.toml
src/bin/cpuid.rs
src/tests/xeon_gold_6252.rs

- Updated clap to 3.1.6 and updated cpuid cli tool accordingly.
- Modified failing test, according to wikichip.org the Xeon gold 6252 does have AVX512VNNI support.

Fixed action pipeline

---

.github/workflows/standard.yml
src/lib.rs

Currently building for a non-conventional x86 target fails with:
```
Compiling raw-cpuid v10.2.0
error[E0433]: failed to resolve: could not find `arch` in `self`
--> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-10.2.0/src/lib.rs:80:37
|
80 |         let result = unsafe { self::arch::__cpuid_count(a, c) };
|                                     ^^^^ could not find `arch` in `self`
```
This is because the target has no SSE, and therefore it has no native cpuid according to this create.
This PR only enables ::native_cpuid and the functions that depend on it, when the target has support for it. 
Targets that by this create are considered to not have native cpuid, can still provide there own function via `CpuId::with_cpuid_fn()`.
If `core::arch::x86::has_cpuid()` stabilizes, it …

Fixed build when native_cpuid is not avalible on target

---

src/lib.rs

Related: #61
AMD CPU supports Leaf: `0x8000_001D` from Family 15h, same format as Intel Leaf: `0x4`.
<https://www.amd.com/system/files/TechDocs/42301_15h_Mod_00h-0Fh_BKDG.pdf>

Implement AMD leaf 0x8000_001D (Cache Properties/Parameters)

---

src/bin/cpuid.rs
src/extended.rs
src/lib.rs
src/tests/ryzen_matisse.rs
src/tests/xeon_gold_6252.rs

Related: #62
It seems that the result of the comment part of the `ryzen_matisse` test file and the CPUID value are different.  
Do you want to leave it as is?
```
///   extended APIC ID = 10
///   Core Identifiers (0x8000001e/ebx):
///      core ID          = 0x5 (5)
///      threads per core = 0x2 (2)
///   Node Identifiers (0x8000001e/ecx):
///      node ID             = 0x0 (0)
///      nodes per processor = 0x1 (1)
```
```
0x8000001e_00000000u64 => CpuIdResult { eax: 0x00000000, ebx: 0x00000100, ecx: 0x00000000, edx: 0x00000000 },
```

 Implement AMD leaf 0x8000_001E (Processor Topology Information)

---

Cargo.toml
src/lib.rs
src/tests/mod.rs

This is a regression from 10.7.0. There's no need for CpuIdReader to support Debug, so drop it.

Restore CpuId's Debug implementation

---

Cargo.toml

Added [`categories`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-categories-field) field to indicate `#![no_std]` compatiblity in `Cargo.toml`. This change makes `raw-cpuid` visible to category-specific pages ([`no-std`](https://crates.io/categories/no-std) and [`no-std::no-alloc`](https://crates.io/categories/no-std::no-alloc)).

Add categories field to Cargo.toml

---

src/lib.rs

WAITPKG was incorrectly set to 1 >> 5, this pull request fixes this.

Fix WAITPKG flag of ExtendedFeaturesEcx structure

---

src/lib.rs

- Changed info: All Avx512 extension features are supported for AMD 
- See AMD whitepaper and wikichips
- No official info on AMD manual though

Update docs regarding Avx512 on AMD

---

Cargo.toml
src/display.rs
src/lib.rs
src/tests/i5_3337u.rs

- Missing Extended features are those located at edx register and for leaf eax=7,ecx=0
- Implemented new struct for features at edx register to contain those features.
- Changed the display code by adding new features implemented.

Implement Missing Extended Features

---

src/display.rs
src/lib.rs
src/tests/i5_3337u.rs
src/tests/ryzen_matisse.rs
src/tests/xeon_gold_6252.rs

- Implementations
- Tests and cli are modified accordingly.

Implementation for Extended Features with subleaf Ecx=0x1

---

Cargo.toml

Without this patch, this fails to compile:
```
cargo test --no-default-features --features serde_json
```

annotate examples/serialize_deserialize.rs with correct features

---

src/lib.rs

Previously, the code used bit 8 of ECX (`ExtendedFeatures::GFNI`) to check for CET shadow stack support. Fix the function to use bit 7 of ECX (`ExtendedFeatures::CETSS`) instead.

Fix detection of CET shadow stacks

---

src/lib.rs
src/tests/i5_3337u.rs

I added these since they were previously not implemented/reserved. I checked and according to the Intel SDM these are only implemented in Intel® Core™ Ultra processor supporting Lunar Lake performance hybrid architecture and Intel® Core™ Ultra processor supporting Lunar Lake performance hybrid architecture so I updated the i5 tests :3

Update Extended Features for Subleaf Eax=1 and Edx=1

---

src/display.rs
src/extended.rs
src/lib.rs
src/tests/ryzen_matisse.rs

Added implementation according to AMDs 24594 Revision 3.36 from March 2024 for Leafs:
- 8000_0020: Testcases included as reading from Ryzen was available
- 8000_0021: Only local testing with display as my proc does support this
- 8000_0022: Only local testing with display as my proc does support this
- 8000_0023: Not tested
- 8000_0026: Not tested

Implemented Leaf 80000020, 21,22,23 and 26
